/**
 * The CLOSED set of environments the worker recognises. Anything else is not a mode we ship —
 * it must not unlock a dev-only path by accident (see `environmentOf`).
 */
export type Environment = "development" | "test" | "production"

/**
 * Read `ENVIRONMENT` as a VALIDATED, typed value, failing CLOSED. The binding arrives as a raw
 * string (wrangler var / .dev.vars). A missing or unrecognized value collapses to "production"
 * (the locked mode) so a dev-only branch can never accidentally unlock. Chiefly used by the
 * request-test harness (ENVIRONMENT="test").
 */
export const environmentOf = (env: Bindings): Environment =>
  env.ENVIRONMENT === "development" || env.ENVIRONMENT === "test" ? env.ENVIRONMENT : "production"

/**
 * Worker bindings. `Env` (DB, KV, BUCKET, ASSETS, LOGIN_RATE_LIMITER) is generated by
 * `wrangler types` into worker-configuration.d.ts; we extend it with the vars/secrets Better
 * Auth and the estimator need. These come from wrangler vars / .dev.vars (BETTER_AUTH_SECRET and
 * OPENROUTER_API_KEY are `wrangler secret`s in production).
 */
export interface Bindings extends Env {
  readonly BETTER_AUTH_SECRET: string
  readonly BETTER_AUTH_URL: string
  /** OpenRouter key for the meal Estimator (the only inference dependency). */
  readonly OPENROUTER_API_KEY: string
  /**
   * Selects per-environment behaviour. "test" = the request-test mode (silent, deterministic);
   * anything else = production. Read it through `environmentOf` to get the validated, fail-closed
   * value rather than trusting the raw string at a privilege boundary.
   */
  readonly ENVIRONMENT: string
}
